version: '3.8'

services:
  redis:
    image: redis
    container_name: redis_for_osm
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./redis-d–∞ta:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always