redis:
  host: "localhost"
  port: 6379
  database: 0 # редис дб не имеют имени, они индексируются с 0
  username_env_name: "REDIS_USER"
  password_env_name: "REDIS_PASSWORD"
telegram_bot:
  token_env_name: "BOT_TOKEN"
  workers_count: 1
osm_broker:
  categories_to_amenities_map:
    "catering":
      "name": "Питание"
      "amenity": [
        "bar",
        "biergarten",
        "cafe",
        "fast_food",
        "food_court",
        "pub",
        "restaurant"
      ]
      "education":
        "name": "Образование"
        "amenity": [
          "college",
          "driving_school",
          "kindergarten",
          "language_school",
          "library",
          "music_school",
          "school",
          "university"
        ]
      "transport":
        "name": "Транспорт"
        "amenity": [
          "bicycle_parking",
          "bus_station",
          "car_wash",
          "vehicle_inspection",
          "charging_station",
          "fuel",
          "motorcycle_parking",
          "parking",
          "taxi"
        ]
      "finance":
        "name": "Финансы"
        "amenity": [
          "atm",
          "bank",
          "bureau_de_change"
        ]
      "health":
        "name": "Здоровье"
        "amenity": [
          "clinic",
          "dentist",
          "doctors",
          "hospital",
          "pharmacy",
          "veterinary"
        ]
      "entertainment":
        "name": "Развлечение"
        "amenity": [
          "casino",
          "cinema",
          "community_centre",
          "conference_centre",
          "events_venue",
          "nightclub",
          "theatre"
        ]
      "other":
        "name": "Другое"
        "amenity": [
          "toilets",
          "recycling",
          "waste_disposal",
          "marketplace"
        ]