redis:
  host: "localhost"
  port: 6379
  database: 0 # редис дб не имеют имени, они индексируются с 0
  username_env_name: "REDIS_USER"
  password_env_name: "REDIS_PASSWORD"
telegram_bot:
  token_env_name: "BOT_TOKEN"
  workers_count: 1
osm_broker:
  categories_to_amenities_map:
    "transport":
        "name": "Транспорт"
        "amenities": ["cafe"]
